site_name: Stardew Valley Journal
site_url: https://sv.pi3.fun/
site_author: Pi3-l22
repo_name: Pi3-l22/stardew-valley
repo_url: https://github.com/Pi3-l22/stardew-valley
nav:
  - 首页说明: index.md
  - Stardew Valley v1.5:
    - 🏳️‍🌈目录汇总: content.md
    - 🧑人物信息:
      - 🏳️‍🌈人物汇总: character/index.md
      - Alex 亚历克斯: character/Alex.md
      - Sebastian 塞巴斯蒂安: character/Sebastian.md
      - Sam 山姆: character/Sam.md
      - Elliott 艾利欧特: character/Elliott.md
      - Harvey 哈维: character/Harvey.md
      - Shane 谢恩: character/Shane.md
      - Abigail 阿比盖尔: character/Abigail.md
      - Emily 艾米丽: character/Emily.md
      - Haley 海莉: character/Haley.md
      - Maru 玛鲁: character/Maru.md
      - Leah 莉亚: character/Leah.md
      - Penny 潘妮: character/Penny.md
      - Evelyn 艾芙琳: character/Evelyn.md
      - George 乔治: character/George.md
      - Robin 罗宾: character/Robin.md
      - Demetrius 德米特里厄斯: character/Demetrius.md
      - Jodi 乔迪: character/Jodi.md
      - Kent 肯特: character/Kent.md
      - Vincent 文森特: character/Vincent.md
      - Marnie 玛妮: character/Marnie.md
      - Jas 贾斯: character/Jas.md
      - Pierre 皮埃尔: character/Pierre.md
      - Calorine 卡洛琳: character/Calorine.md
      - Pam 潘姆: character/Pam.md
      - Gus 格斯: character/Gus.md
      - Clint 克林特: character/Clint.md
      - Willy 威利: character/Willy.md
      - Lewis 刘易斯: character/Lewis.md
      - Linus 莱纳斯: character/Linus.md
      - Sandy 桑迪: character/Sandy.md
      - Wizard 法师: character/Wizard.md
      - Dwarf 矮人: character/Dwarf.md
      - Krobus 科罗布斯: character/Krobus.md
      - Leo 雷欧: character/Leo.md
    - 🎁礼物喜好: gift.md
    - 🏝️地点信息: place.md
    - 🛠️打造清单: build.md
    - 🪓木匠建造清单: carpenter.md
    - ⛏️铁匠农具升级清单: blacksmith.md
    - ⚔️战斗物品清单: battle.md
    - ⚙️工匠制品清单: craftsman.md
    - 📝食谱清单: recipe.md
    - 📦收集包清单: collect.md
    - 🏜️素材收集地点(全季): material.md
    - 🗺️四季地图:
      - 🏳️‍🌈地图汇总: season_map/index.md
      - 🌄春季地图: season_map/spring.md
      - 🏖️夏季地图: season_map/summer.md
      - 🏕️秋季地图: season_map/fall.md
      - 🏔️冬季地图: season_map/winter.md
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: images/logo.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github-alt
  feature:
    - announce.dismiss  # 顶部公告栏
    - content.action.edit  # 源码编辑
    - content.action.view  # 源码浏览
    - content.code.annotate  # 代码注释
    - content.code.copy  # 代码复制
    # - content.code.select  # 代码选择
    # - content.footnote.tooltips  # 脚注工具提示
    # - content.tabs.link  # 标签链接
    - content.tooltips  # 工具提示
    # - header.autohide  # 自动隐藏标题栏
    - navigation.expand  # 导航展开
    - navigation.footer  # 底部上一页下一页导航
    - navigation.indexes  # 索引导航
    # - navigation.instant  # 即时导航
    # - navigation.instant.prefetch  # 即时导航预取
    # - navigation.instant.progress  # 即时导航进度
    # - navigation.prune  # 导航修剪
    - navigation.sections  # 导航章节
    - navigation.tabs  # 导航标签
    # - navigation.tabs.sticky  # 导航标签粘性
    - navigation.top  # 返回顶部导航
    - navigation.tracking  # 导航跟踪
    - search.highlight  # 搜索高亮
    - search.share  # 搜索分享
    - search.suggest  # 搜索建议
    - toc.follow  # 目录跟随
    # - toc.integrate  # 目录集成
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

extra:
  generator: false  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pi3-l22
    - icon: fontawesome/brands/twitter
      link: https://x.com/liu622511?s=09
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/lc_622_511
    - icon: fontawesome/solid/envelope
      link: mailto:622.511.liuchao@gmail.com

copyright: Copyright &copy; 2021 - 2024 By Pi3-l22

